[package]
name = "sux"
version = "0.1.1"
edition = "2021"
description = "A pure Rust implementation of succinct and compressed data structures"
repository = "https://github.com/vigna/sux-rs/"
license = "Apache-2.0 OR LGPL-2.1-or-later"
readme = "README.md"
keywords = ["succinct", "rank", "select"]
categories = ["compression", "data-structures"]

[dependencies]
anyhow = "1.0.71"
bitflags = "2.3.1"
bytemuck = "1.13.1"
common_traits = "0.10.0"
libc = "0.2.147"
log = "0.4.17"
mmap-rs = "0.5.0"
num_cpus = "1.16.0"
num-traits = "0.2.15"
rayon = {version="1.7.0", optional=true}
stable_deref_trait = "1.2.0"
yoke = "0.7.1"
epserde = "0.2.0"
bitvec = "1.0.1"
clap = { version = "4.2.7", features = ["derive"] }
dsi-progress-logger = "0.2.1"
stderrlog = "0.5.4"
rand = {version="0.8.5", features=["small_rng"]}
zstd = "0.12.4"
tempfile = "3.8.0"
xxh3 = "0.1.1"
lender = "0.2.0"
arbitrary-chunks = "0.4.1"
derive_setters = "0.1.6"
flate2 = "1.0.28"
derivative = "2.2.0"
rdst = "0.20.11"
arbitrary = { version = "1", features = ["derive"], optional=true }
mem_dbg = "0.1"

[features]
default = ["rayon"]
fuzz = ["dep:arbitrary"]
slow = [] # Run slow tests (use --release)

[profile.release]
opt-level = 3             # like --release
lto = "fat"               # Full LTO
overflow-checks = false   # Disable integer overflow checks.
debug = true              # Include debug info.
debug-assertions = false  # Enables debug assertions.
codegen-units=1           # slower compile times, but maybe better perf
